version: '3.4'

services:

  nginx: 
    image: nginx:latest
    container_name: jr_revprox_nginx
    ports:
      - 90:90
      - 91:91
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./error.log:/etc/nginx/error_log.log
      - ./cache/:/etc/nginx/cache
      - ./data:/data
    networks:
    - portalnet      

networks:
  portalnet:

